const DISCORD_LINK = '[Generated by CatchGrid](https://dex.cjdev.app/)';
export const STANDARD_DISCORD_MESSAGE_LIMIT = 2_000;
export const NITRO_DISCORD_MESSAGE_LIMIT = 4_000;
const DISCORD_BODY_RESERVE = 100;

export interface DiscordSection {
  label: string;
  strings: readonly string[];
}

export interface DiscordMessageOptions {
  maxLength?: number;
}

export function buildDiscordMessages(
  sections: readonly DiscordSection[],
  options: DiscordMessageOptions = {},
): string[] {
  const messageLimit = options.maxLength ?? STANDARD_DISCORD_MESSAGE_LIMIT;
  if (!Number.isSafeInteger(messageLimit) || messageLimit <= DISCORD_BODY_RESERVE) {
    throw new RangeError('maxLength must leave room for Discord message formatting');
  }
  const bodyLimit = messageLimit - DISCORD_BODY_RESERVE;
  const blocks = sections.flatMap((section) =>
    section.strings.map((value, index) => {
      const suffix = section.strings.length > 1 ? ` (${index + 1}/${section.strings.length})` : '';
      return `**${section.label}${suffix}**\n\`\`\`text\n${value}\n\`\`\``;
    }),
  );
  if (blocks.length === 0) return [];

  const messages: string[] = [];
  let current = '**My missing Dex needs**';
  for (const block of blocks) {
    const candidate = `${current}\n\n${block}`;
    if (candidate.length <= bodyLimit) {
      current = candidate;
      continue;
    }
    if (current !== '**My missing Dex needs**') messages.push(current);
    current = `**My missing Dex needs (continued)**\n\n${block}`;
  }
  messages.push(current);

  const finalWithLink = `${messages.at(-1)}\n\n${DISCORD_LINK}`;
  if (finalWithLink.length <= messageLimit) messages[messages.length - 1] = finalWithLink;
  else messages.push(DISCORD_LINK);
  return messages;
}
