const DISCORD_LINK = '[Generated by CatchGrid](https://dex.cjdev.app/)';
const DISCORD_MESSAGE_LIMIT = 2_000;
const DISCORD_BODY_LIMIT = 1_900;

export interface DiscordSection {
  label: string;
  strings: readonly string[];
}

export function buildDiscordMessages(sections: readonly DiscordSection[]): string[] {
  const blocks = sections.flatMap((section) =>
    section.strings.map((value, index) => {
      const suffix = section.strings.length > 1 ? ` (${index + 1}/${section.strings.length})` : '';
      return `**${section.label}${suffix}**\n\`\`\`text\n${value}\n\`\`\``;
    }),
  );
  if (blocks.length === 0) return [];

  const messages: string[] = [];
  let current = '**My missing Dex needs**';
  for (const block of blocks) {
    const candidate = `${current}\n\n${block}`;
    if (candidate.length <= DISCORD_BODY_LIMIT) {
      current = candidate;
      continue;
    }
    messages.push(current);
    current = `**My missing Dex needs (continued)**\n\n${block}`;
  }
  messages.push(current);

  const finalWithLink = `${messages.at(-1)}\n\n${DISCORD_LINK}`;
  if (finalWithLink.length <= DISCORD_MESSAGE_LIMIT) messages[messages.length - 1] = finalWithLink;
  else messages.push(DISCORD_LINK);
  return messages;
}
