import { describe, expect, it } from 'vitest';
import {
  buildDiscordMessages,
  NITRO_DISCORD_MESSAGE_LIMIT,
  STANDARD_DISCORD_MESSAGE_LIMIT,
} from '../../src/lib/discordShare';

describe('Discord missing-Dex sharing', () => {
  it('formats selected categories as copyable code blocks with the CatchGrid footer', () => {
    const [message] = buildDiscordMessages([
      { label: 'XXL', strings: ['!traded&xxl&1-25'] },
      { label: 'XXS', strings: ['!traded&xxs&1-25'] },
    ]);

    expect(message).toContain('**My missing Dex needs**');
    expect(message).toContain('**XXL**\n```text\n!traded&xxl&1-25\n```');
    expect(message).toContain('**XXS**\n```text\n!traded&xxs&1-25\n```');
    expect(message).toMatch(/\[Generated by CatchGrid\]\(https:\/\/dex\.cjdev\.app\/\)$/);
  });

  it('splits long category blocks without exceeding Discord limits or breaking code fences', () => {
    const messages = buildDiscordMessages([
      { label: 'XXL', strings: [`!traded&xxl&${'1,'.repeat(700)}`] },
      { label: 'XXS', strings: [`!traded&xxs&${'2,'.repeat(700)}`] },
    ]);

    expect(messages.length).toBeGreaterThan(1);
    expect(messages.every((message) => message.length <= STANDARD_DISCORD_MESSAGE_LIMIT)).toBe(
      true,
    );
    expect(
      messages.slice(0, -1).every((message) => !message.includes('Generated by CatchGrid')),
    ).toBe(true);
    expect(messages.at(-1)).toContain('Generated by CatchGrid');
    for (const message of messages) {
      expect((message.match(/```/g) ?? []).length % 2).toBe(0);
    }
  });

  it('uses the Nitro limit to keep a larger share in one message', () => {
    const sections = [
      { label: 'XXL', strings: [`!traded&xxl&${'1,'.repeat(700)}`] },
      { label: 'XXS', strings: [`!traded&xxs&${'2,'.repeat(700)}`] },
    ];

    expect(buildDiscordMessages(sections).length).toBeGreaterThan(1);

    const nitroMessages = buildDiscordMessages(sections, {
      maxLength: NITRO_DISCORD_MESSAGE_LIMIT,
    });
    expect(nitroMessages).toHaveLength(1);
    expect(nitroMessages[0]?.length).toBeLessThanOrEqual(NITRO_DISCORD_MESSAGE_LIMIT);
    expect(nitroMessages[0]).toContain('Generated by CatchGrid');
  });

  it('returns no message when no missing lists are selected', () => {
    expect(buildDiscordMessages([])).toEqual([]);
  });
});
