import { describe, expect, it } from 'vitest';
import { buildDiscordMessages } from '../../src/lib/discordShare';

describe('Discord missing-Dex sharing', () => {
  it('formats selected categories as copyable code blocks with the Dexly footer', () => {
    const [message] = buildDiscordMessages([
      { label: 'XXL', strings: ['!traded&xxl&1-25'] },
      { label: 'XXS', strings: ['!traded&xxs&1-25'] },
    ]);

    expect(message).toContain('**My missing Dex needs**');
    expect(message).toContain('**XXL**\n```text\n!traded&xxl&1-25\n```');
    expect(message).toContain('**XXS**\n```text\n!traded&xxs&1-25\n```');
    expect(message).toMatch(
      /\[Generated by Dexly\]\(https:\/\/dexly-companion\.codyleejohnson26\.workers\.dev\/\)$/,
    );
  });

  it('splits long category blocks without exceeding Discord limits or breaking code fences', () => {
    const messages = buildDiscordMessages([
      { label: 'XXL', strings: [`!traded&xxl&${'1,'.repeat(700)}`] },
      { label: 'XXS', strings: [`!traded&xxs&${'2,'.repeat(700)}`] },
    ]);

    expect(messages.length).toBeGreaterThan(1);
    expect(messages.every((message) => message.length <= 2_000)).toBe(true);
    expect(messages.slice(0, -1).every((message) => !message.includes('Generated by Dexly'))).toBe(
      true,
    );
    expect(messages.at(-1)).toContain('Generated by Dexly');
    for (const message of messages) {
      expect((message.match(/```/g) ?? []).length % 2).toBe(0);
    }
  });

  it('returns no message when no missing lists are selected', () => {
    expect(buildDiscordMessages([])).toEqual([]);
  });
});
